CREATE TABLE eoi (
    EOInumber INT AUTO_INCREMENT PRIMARY KEY,
    JobReference VARCHAR(5) NOT NULL,
    FirstName VARCHAR(20) NOT NULL,
    LastName VARCHAR(20) NOT NULL,
    Gender ENUM('Male', 'Female', 'Other') NOT NULL,
    StreetAddress VARCHAR(40) NOT NULL,
    Suburb VARCHAR(40) NOT NULL,
    State VARCHAR(3) NOT NULL,
    Postcode VARCHAR(4) NOT NULL,
    EmailAddress VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(12) NOT NULL,
    Skill1 VARCHAR(255),
    Skill2 VARCHAR(255),
    Skill3 VARCHAR(255),
    Skill4 VARCHAR(255),
    Skill5 VARCHAR(255),
    OtherSkills TEXT,
    Status ENUM('New', 'Current', 'Final') DEFAULT 'New'
);
