CREATE TABLE [jobs] (
  [job_ref_j] varchar(5) NOT NULL,
  [job_title_j] varchar(100) NOT NULL,
  [description_j] text NOT NULL,
  [essential_qualification_j] text DEFAULT NULL,
  [salary_range_j] varchar(50) DEFAULT NULL,
  [key_responsibility_j] text DEFAULT NULL,
  [report_to_j] varchar(50) DEFAULT NULL,
  [preferable_qualification_j] text DEFAULT NULL,
  [brief_description_j] text DEFAULT NULL
);

INSERT INTO [jobs] ([job_ref_j], [job_title_j], [description_j], [essential_qualification_j], [salary_range_j], [key_responsibility_j], [report_to_j], [preferable_qualification_j], [brief_description_j]) VALUES
('CEN19', 'Cloud Engineer', 'As a Cloud Engineer, you will design, implement, and maintain cloud-based systems to support the organization''s digital infrastructure and business needs.', 'Bachelor''s degree in Computer Science, Information Technology, or a related field.\r\n3+ years of experience in cloud engineering or related roles.\r\nProficiency in programming languages like Python, Java, or Ruby.\r\nFamiliarity with major cloud platforms like AWS, Azure, or Google Cloud Platform.\r\nStrong understanding of networking concepts, protocols, and security.', '$105,000 to $125,000 annually', 'Design and implement cloud solutions that meet specific business needs.\r\nDevelop, deploy, and maintain cloud-native applications and services.\r\nManage and maintain the cloud infrastructure, including virtual networks, storage, and compute resources.\r\nTroubleshoot issues, optimize performance, and ensure the security and reliability of cloud-based systems.\r\nCollaborate with other IT professionals, such as cloud architects, DevOps engineers, and software engineers.', 'Cloud Solutions Architect', 'Certifications such as AWS Certified Solutions Architect or Microsoft Azure Administrator.\r\nExperience with containerization tools like Docker or Kubernetes.', 'As a cloud engineer, you are a technical expert who helps companies succeed with cloud-based storage, services, and infrastructure by building, maintaining, provisioning, securing, and optimizing digital systems that operate using cloud technology.'),
('CSS44', 'Cybersecurity Specialist', 'As a Cybersecurity Specialist, your role is to safeguard the organization''s IT infrastructure by implementing security measures, detecting threats, and responding to incidents.\r\n', 'Master''s degree in Cybersecurity, Computer Science, or related field.\r\n5+ years of experience in cybersecurity roles.\r\nProficiency in network protocols, firewalls, and intrusion detection systems.\r\nStrong knowledge of encryption and decryption techniques.', '$133,454 to $190,050 annually', 'Develop and enforce security policies and procedures.\r\nMonitor networks for suspicious activity and respond to incidents.\r\nConduct security assessments and audits to identify vulnerabilities.\r\nImplement and maintain firewalls, encryption, and intrusion detection systems.\r\nProvide training to staff on cybersecurity best practices.', 'Chief Information Security Officer (CISO)', 'Certifications such as CISSP, CEH, or CISM.\r\nExperience with Python or other scripting languages.', 'As a cybersecurity specialist, also known as an information security analyst, your job is to protect computer systems, networks, and data from unauthorized access, theft, or damage by implementing security measures, detecting threats, and responding to security incidents.'),
('ITT02', 'IT Support Technician', 'As an IT Support Technician, you will provide technical support to clients, troubleshoot hardware and software issues, and ensure the smooth operation of IT systems.', 'Associate''s degree in Information Technology or a related field.\r\n2+ years of experience in IT support or a similar role.\r\nStrong knowledge of computer hardware, software, and networking.\r\nExcellent problem-solving skills and attention to detail.', '$60,000 to $80,000 annually', 'Identify and resolve issues with computer hardware, software, and networks.\r\nProvide technical assistance to users via phone, email, or in-person.\r\nInstall and configure computer systems and applications.\r\nMaintain records of technical issues, solutions, and user interactions.\r\nAssist users with technical issues and provide guidance on IT tools and systems.', 'IT Support Manager', 'Certifications such as CompTIA A+ or Network+.\r\nExperience with help desk software and remote support tools.', 'As an IT Support Technician, you will be responsible for providing technical support to our clients, troubleshooting hardware and software issues, and ensuring the smooth operation of IT systems.');